# Generated by Django 5.0 on 2024-01-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_books_price_alter_books_authorname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='book_photo/'),
        ),
    ]
